name: test1-complete

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      sonarUrl:
        required: false
        default: http://ns3266246.ip-5-39-79.eu:9000/
      sonarToken:
        required: false
        default:
      targetPath:
        description: 'Target directory of build process.'
        required: false
        type: string
        default: './'


env:
  targetPath: ${{ github.event.inputs.targetPath || './' }}
  sonarUrl: ${{ github.event.inputs.sonarUrl || 'http://ns3266246.ip-5-39-79.eu:9000/' }}
  sonarToken: ${{ github.event.inputs.sonarToken || secrets.SONARQUBE_TOKEN }}


jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the application
        run: .github/workflows/scripts/build.sh

      - name: Archiving artifact
        run: pwd;ls -l;tar -cvf ./BuildOutput.tar -C ${{ env.targetPath }}/ .

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuildOutput
          path: ./BuildOutput.tar

#   Test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Test
        run: .github/workflows/scripts/test.sh

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/TEST-*.xml'
  
  # Quality:
  #   name: SonarQube analysis
  #   runs-on: ubuntu-latest   
  #   steps:
      # - name: Checkout the repository
      #   uses: actions/checkout@v2

      - name: SonarQube analysis
        run: .github/workflows/scripts/quality.sh.template
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_URL: ${{ env.sonarUrl }}
          PROJECT_PATH: .
